### ISSUE TITLE
Enhancement - URL signature

### ISSUE THREAD

**Issue by janklimo** [scaleflex/react-cloudimage-responsive-blur-hash#1]
Big fan of the package @dzmitry-stramavus 👏 

I'm looking for a way to implement URL signatures on the client. I'm fully aware this will never be 100% secure but all I need is preventing users from editing the URL to remove watermarks. With the help of tools like [gnirts](https://anseki.github.io/gnirts/) it would be pretty easy to obfuscate salt in the source well enough to take a significant effort to crack. I'm thinking if discouraging elementary tinkering with URLs is of enough value to have this as an opt-in feature.

One possibility is having a `signature` prop on `Img`. Here's what it could look like:

```js
<Img
  src={thumbnail_grid_src}
  signature={(path) => computeSignature(path)}
/>
```

where it's up to the user to implement the `computeSignature` function themselves to keep this package lean. `Img` component appends it at the end of the URL and renders the image.

Looking for your feedback @dzmitry-stramavus. Happy to help if you think it adds value 👍

**Comment by dzmitry-stramavus** [comment]
hey @janklimo, thx for the feedback!

Yes, sounds really good to us. I'll implement it during the week.
